version: "3.9"
services:
  komobox:
    build: ./komobox
    environment:
      ENDPOINT: http://minikom:8080/event
    depends_on:
      - minikom
  minikom:
    build: ./server
    ports:
      - 8080:8080
